apiVersion: apps/v1
kind: Deployment
metadata:
  name: enabel
  namespace: developement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enabel
  template:
    metadata:
      labels:
        app: enabel
    spec:
      containers:
      - name: enabel
        image: 174391158959.dkr.ecr.eu-west-3.amazonaws.com/enabel:e6245a0
        ports:
        - containerPort: 80
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "general_workloads"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/purpose
                    operator: In
                    values:
                      - general_workloads

--- 
apiVersion: v1
kind: Service
metadata:
  name: enabel
  namespace: developement
spec:
  selector:
    app: enabel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enabel
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  rules:
    - host: snis.smartmssa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enabel
                port:
                  number: 80
  tls:
    - hosts:
        - snis.smartmssa.com
